"""Build kaggle/kernel/run.py: the repo's src/ and bench/ embedded as a base64 tarball, then the
real benchmark runs unchanged on a Kaggle T4. Push with `uvx kaggle kernels push -p kaggle/kernel`."""

import base64
import io
import json
import sys
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
buf = io.BytesIO()
with tarfile.open(fileobj=buf, mode="w:gz") as tar:
    for d in ("src", "bench", "tests"):
        tar.add(ROOT / d, arcname=d, filter=lambda t: None if "__pycache__" in t.name else t)
blob = base64.b64encode(buf.getvalue()).decode()
mode = sys.argv[1] if len(sys.argv) > 1 else "bench"
triton_version = sys.argv[2] if len(sys.argv) > 2 else "3.2.0"
out = ROOT / "kaggle" / "kernel"
out.mkdir(parents=True, exist_ok=True)
(out / "run.py").write_text(
    f'''"""triton-attn: correctness tests and benchmark on a Kaggle T4.
Generated by kaggle/build.py from the triton-attn repo; runs the repo's own tests and bench."""
import base64, io, os, shutil, subprocess, sys, tarfile
os.chdir("/kaggle/working")
tarfile.open(fileobj=io.BytesIO(base64.b64decode("{blob}")), mode="r:gz").extractall(".")
env = dict(os.environ, PYTHONPATH="src")
run = lambda *a: subprocess.run([sys.executable, *a], check=True, env=env)
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "pytest"], check=True)
subprocess.run(["nvidia-smi"], check=False)
r = subprocess.CompletedProcess([], 0)
MODE = os.environ.get("TATTN_KAGGLE_MODE", "@@MODE@@")
os.makedirs("results", exist_ok=True)
if MODE == "diagnose":
    # Which Triton releases still emit tensor-core code for sm75? Try each in turn.
    for ver in ["3.6.0", "3.5.1", "3.5.0", "3.4.0", "3.3.1", "3.3.0", "3.2.0", "3.1.0", "3.0.0", "2.3.1"]:
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", f"triton=={{ver}}"], check=False)
        with open(f"results/diagnose-log-triton-{{ver}}.txt", "w") as log:
            subprocess.run([sys.executable, "bench/diagnose.py"], check=False, env=env, stdout=log, stderr=subprocess.STDOUT)
else:
    # Triton >= 3.3 emits no tensor-core (mma) code for sm75 (see results/diagnose-*.json); 3.2.0 does.
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "triton==@@TRITON@@"], check=True)
    with open("gpu-tests.txt", "w") as log:
        r = subprocess.run([sys.executable, "-m", "pytest", "-q", "tests"], env=env, stdout=log, stderr=subprocess.STDOUT)
    print(open("gpu-tests.txt").read()[-2000:])
    run("bench/bench.py", "--out", "results/t4.json")
shutil.rmtree("src"); shutil.rmtree("bench"); shutil.rmtree("tests")
sys.exit(r.returncode)
'''.replace("@@MODE@@", mode).replace("@@TRITON@@", triton_version)
)
(out / "kernel-metadata.json").write_text(
    json.dumps(
        {
            "id": "amaanmithani/triton-attn-bench",
            "title": "triton-attn bench",
            "code_file": "run.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": True,
            "machine_shape": "NvidiaTeslaT4",
            "enable_internet": True,
            "dataset_sources": [],
            "competition_sources": [],
            "kernel_sources": [],
        },
        indent=2,
    )
)
print("built", len(blob), "bytes of source")
